---

- name: configure dphys swapfile size
  ansible.builtin.lineinfile:
    path: /etc/dphys-swapfile
    regexp: '^CONF_SWAPSIZE='
    line: "#CONF_SWAPSIZE=100"
  notify: restart service

- name: configure dphys swapfile factor
  ansible.builtin.lineinfile:
    path: /etc/dphys-swapfile
    regexp: 'CONF_SWAPFACTOR='
    line: "CONF_SWAPFACTOR={{ rpi_swap_factor }}"
  notify: restart service
