---

- name: Ensure package is installed (thx to screenly-ose for removing it)
  ansible.builtin.package:
    name: dphys-swapfile
    state: present

- name: Configure dphys swapfile size
  ansible.builtin.lineinfile:
    path: /etc/dphys-swapfile
    regexp: '^CONF_SWAPSIZE='
    line: "#CONF_SWAPSIZE=100"
  notify: Restart dphys-swapfile service

- name: Configure dphys swapfile factor
  ansible.builtin.lineinfile:
    path: /etc/dphys-swapfile
    regexp: 'CONF_SWAPFACTOR='
    line: "CONF_SWAPFACTOR={{ rpi_swap_factor }}"
  notify: Restart dphys-swapfile service

- name: Enable dphys swapfile
  ansible.builtin.service:
    name: dphys-swapfile.service
    enabled: true
    state: started
